### ISSUE TITLE
Android: Incorrect buy value calculation for stock 

### ISSUE THREAD

**Issue by mnsrt** [mystocksportfolio/issues#381]
Description: There seems to be an error in calculating the buy value for stocks in the app. I have purchased 739 shares of XX.YY stock at a price of €9.8676 each, which should total €7294.1564, so, rounding it to two decimal places, it should be €7292.16 . However, the app shows a buy value of €7292.13, which is incorrect.
Please verify and correct the calculation logic.

Steps to reproduce:
Enter a purchase of 739 shares of a stock at a price of €9.8676
Observe the calculated buy value shown in the portfolio.

Expected behavior: The buy value should be calculated as: 739 shares * €9.8676 = €7294.16

Actual behavior: The app shows the buy value as €7292.13, which is slightly lower than the actual value.

App version: 2.982
![image](https://github.com/user-attachments/assets/4d5ff564-386e-4f49-b7fa-b8712e765b23)

**Comment by mikezliu** [comment]
I'm not able to repro (See screenshot)

<img width="404" alt="image" src="https://github.com/user-attachments/assets/70911b89-7073-4270-bd4b-0c48259d3d4e">

It's possible you have more decimals in the transaction that's not set to show on this page due to 4 decimal precision. For example 9.8675612345 * 739 would round to 7292.13 and not 7292.16
